### ISSUE TITLE
[Pre-RFC] Enhanced access controls

### ISSUE THREAD

**Issue by actgardner** [pachyderm/rfcs#12]
**Please describe the problem your proposed RFC is trying to address.**
The current implementation of access controls seems difficult to scale to many users, and not amenable to collaboration. With auth enabled:

- Repos default to being visible only to the user who created them.
- Users have to be granted access to repos individually with `pachctl auth set`.
- The `admin` role is extremely broad - it allows accessing every repo, but it also permits operations like configuring external auth providers. 
- Without admins, it's easy for a repo to be "orphaned" if a user exits the system without granting other users access to that repo.

Especially with the addition of external auth providers, it would be convenient to sync group membership and grant access at the group level.

**Describe the solution you'd like**
- Introduce the concept of arbitrary, user-defined groups.
  - This requires RPCs and CLIs for CRUD operations on groups

- Support granting the existing access levels (owner, writer, reader) on a repo to groups as well as individual users.
  - This could look like the existing `pachctl auth set` command, but with the subject prefixed by the type (like GCP's IAM bindings). Ex. `pachctl auth set group:my-group OWNER my-repo`

- Support granting the existing access levels on a repo to "everyone", a group that automatically includes every authenticated user.
   - Once again copying GCP, this could just look like `everyone`

- Support a default ACL for new repos created on the cluster, configurable by admins, ex. "everyone can read every new repo".
  - Setting the default ACL for the cluster is probably an admin task.

- Rename the current admin role to "superadmin".

- Create a new admin role which has the "owner" permission on every file, but can't perform cluster administration tasks like configuring authentication. 

This seems like a superset of our existing functionality, so it should be easy to migrate existing repos.

**Describe alternatives you've considered**
The admin/superadmin role change is mostly orthogonal to adding groups, so we could adopt one but not the other. 

Rather than having an admin role, we could expose more granular access controls for the system itself (in addition to repos). So any user or group could have the "owns all repos" permission pach-wide, or the "can configure auth" permission. This adds more complexity - the ACLs wouldn't be attached to a repo for one - so it seems reasonable to delay this change until we have more concrete use cases. 
 
**Open Questions**
- Should we support nested group membership?

**Additional context**
gcloud's add-iam-policy-binding as a reference for managing ACL entries: https://cloud.google.com/sdk/gcloud/reference/projects/add-iam-policy-binding

**Comment by actgardner** [comment]
/cc @jdoliner @chainlink @nitinjainsj @pappasilenus 

This is the result of some discussion of about Hub access controls. For 1.0 having a less super-powered admin role would be sufficient if we make everyone an admin, so we might be able to scope this down initially.

**Comment by jdoliner** [comment]
This all seems reasonable to me. One question I'm not sure this answer: what is the default value for the default acl. My sense from this proposal is that it should default to visible to everyone, writable only by the creator, but not totally sure. @msteffen would be the best person to comment on the details here, he has a lot of experience with auth systems in general and wrote ours.

**Comment by JoeyZwicker** [comment]
> Support a default ACL for new repos created on the cluster, configurable by admins, ex. "everyone can read every new repo".

One common option that users may want here is something like "inherit from inputs". This may be complicated based on multiple inputs, but the overall idea is some way to say "every user that would have had permissions to create the pipeline/repo I just did should also have access to the output repo." It's maybe a complicated notion that I haven't thought through in great detail, but it fits with the ideas of groups. If anyone on the "data science" group can create pipeline `foo` that takes `bar` as input, then everyone in that group should also inherit the same access for repo `foo`

**Comment by nitinjainsj** [comment]
@actgardner This looks like a good desired goal. Do we need to support groups in core pach for Hub v1.0?

**Comment by actgardner** [comment]
@nitinjainsj I think if we can add the less-powerful admin role we can simply do 1.0 with everyone as admins. As a stretch we could try and add better ACLs but I think Joey is right and we should think through the default access controls for new repos and pipelines.

**Comment by msteffen** [comment]
I can respond to a few pieces of this. The good news is that we're actually part way to many of these.

> This requires RPCs and CLIs for CRUD operations on groups

We actually have RPCs for this now: https://github.com/pachyderm/pachyderm/blob/master/src/client/auth/auth.proto#L485-L488
Currently, though, those RPCs can only be called by admins:
https://github.com/pachyderm/pachyderm/blob/master/src/server/auth/server/api_server.go#L2006-L2011
I think it would make sense to open them up, but at least one open question that should be resolved is how that would interact with SAML. Currently, we only use those calls when a cluster has SAML authentication enabled—we read all of a user's group memberships from the signed SAML assertion that they present during authentication and copy them to etcd. I think we'd want to set it up so that if a user has SAML enabled then we basically keep leaning on the ID provider's groups (so lock this API down), but for Hub users can manage their own groups.

> Support granting the existing access levels (owner, writer, reader) on a repo to groups as well as individual users. This could look like the existing pachctl auth set command, but with the subject prefixed by the type (like GCP's IAM bindings). Ex. pachctl auth set group:my-group OWNER my-repo

This is actually how it works in the SAML case (though we prefix with `group/<IDP name>:<group name>`): https://github.com/pachyderm/pachyderm/blob/master/src/server/auth/server/saml.go#L89. I agree that for manually-managed groups, `group` or `group/pachyderm` or some such are all fine (as long as we prohibit an IDP named `group` in the former case, and an IDP named `pachyderm` in the latter case)

Some more general thoughts:
* I think the part of this re:adding a new admin role makes sense. Two questions:
  * I think two things that current admins can do that aren't mentioned but might be interesting are 1) impersonate users (mint tokens or OTPs for them) and 2) `DeleteAll()`?
  * I know there was initially and may still be some admin-specific logic in the dash (the dash changes what it displays depending on what the user can access, which is why it has auth logic in it at all), so that might need to be be part of this change.
* I think we've been unhappy with the ad-hoc nature of Pachyderm auth for a while, and have talked about using an existing auth system (like Vault?) to manage our ACLs instead. This raises the question of when we might want to do that work relative to these other changes

**Comment by chainlink** [comment]
I think the SAML approach of inheriting the group from the IDP is actually closer to what we want here, so perhaps promoting that to be more core might make sense.

**Comment by actgardner** [comment]
I'm going to put together a more cohesive groups proposal now that I have more context.
